<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmployeeSeeder extends Seeder
{
    public $employees = [
        [
            "Telhalia, M.Th., D.Th",
            "P",
            "Palangka Raya",
            "26 June 1970",
            "Jl. G.Obos XIV No. 138b",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081250846726",
            "Menikah",
            "1",
            "3971880",
            "0",
            "0",
            "1",
            "3889200"
        ],
        [
            "Dr. Prasetiawati, M.Th",
            "P",
            "Tumbang Habaon",
            "26 February 1977",
            "Jl. RTA. Milono KM.8,5, Komplek Kereng Indah Permai II No 13 Kel Sabaru, Kec Sebangau",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085246903260",
            "Menikah",
            "1",
            "3694270",
            "0",
            "0",
            "1",
            "4349290"
        ],
        [
            "Tirta Susila, D.Th",
            "P",
            "Palangka Raya",
            "21 June 1973",
            "Jl. Yogyakarta Komp. Betang Griya Blok A No. 36",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085249331930",
            "Menikah",
            "1",
            "4086140",
            "0",
            "0",
            "1",
            "4260800"
        ],
        [
            "Dr. Suwarsono S.PAK., M.M",
            "L",
            "Gunung Kidul",
            "16 November 1967",
            "Jl. Tampung Penyang",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081310803725",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "11670000"
        ],
        [
            "Suprianto, S.PAK.",
            "L",
            "Aruk,Kapuas",
            "05 July 1968",
            "Jl. Panenga Raya VII",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "08125153246",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "5079340"
        ],
        [
            "Dr. Maidiantius Tanyid, M.Th",
            "L",
            "Makassar",
            "05 May 1977",
            "Jl. Buntu Pantan Tana Toraja",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "082271488811",
            "Menikah",
            "1",
            "3733030",
            "0",
            "0",
            "1",
            "4177260"
        ],
        [
            "Urbanus, M.Th",
            "L",
            "Kab. Sintang",
            "15 June 1976",
            "JL. Kesehatan Komplek Sehat Sejahtera No. A3, Kel. Kota Baru, Kec. Pontianak Selatan",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "085252539090",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Dr. Rina Teriasi, S.Th., M.Si.",
            "P",
            "Kasongan",
            "20 February 1974",
            "Jl.Manunggal IV No.73, Kel. Langkai, Kec. Pahandut",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081349202152",
            "Menikah",
            "1",
            "3961405",
            "0",
            "0",
            "1",
            "4306480"
        ],
        [
            "Dr. Stynie Nova Tumbol, M.Th",
            "P",
            "Ternate",
            "25 August 1972",
            "Jl. Kalibata Blok K No. 03",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "082157928655",
            "Menikah",
            "1",
            "3961405",
            "0",
            "0",
            "1",
            "987185"
        ],
        [
            "Berth Penny Pahan, M.Pd.",
            "L",
            "Banjarmasin",
            "06 September 1970",
            "Jl. Bukit Raya No 87",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081255100846",
            "Menikah",
            "1",
            "4496330",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Silvia Rahmelia, M.Pd",
            "P",
            "Kota Tasikmalaya",
            "12 July 1993",
            "Jl. G Obos No 70",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081220473715",
            "Menikah",
            "1",
            "3155330",
            "0",
            "0",
            "1",
            "1835685"
        ],
        [
            "Yoan Colina, M.AP",
            "P",
            "Palangka Raya",
            "27 June 1990",
            "Jl. Antang 1 No.73",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "082132323028",
            "Menikah",
            "1",
            "3155330",
            "0",
            "0",
            "1",
            "1835685"
        ],
        [
            "Pribadyo Prakosa, S.Si., M.Si.Teol",
            "L",
            "Palangka Raya",
            "25 June 1985",
            "Jl. Damang Leman No.2, Kel. Menteng, Kec. Jekan Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081328731564",
            "Menikah",
            "1",
            "3840375",
            "0",
            "0",
            "1",
            "1140500"
        ],
        [
            "Sri Angellyna, M.Th",
            "P",
            "Kab. Kotawaringin Barat",
            "17 June 1985",
            "Jl. Cilik Riwut Gg Bethel No 02",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085248213667",
            "Menikah",
            "1",
            "3155330",
            "0",
            "0",
            "1",
            "1809770"
        ],
        [
            "Merilyn, M.Th",
            "P",
            "Palangka Raya",
            "13 April 1978",
            "Jl. G.Obos XVII Komp. Timitra 29",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085348507171",
            "Menikah",
            "1",
            "3723145",
            "0",
            "0",
            "1",
            "1263900"
        ],
        [
            "Oktani Haloho, M.Sc",
            "P",
            "Kab. Simalungun",
            "26 October 1990",
            "Jl. Tampung Penyang II A RTA.Milono Km.6 Perum Kayzar B No 9",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "082370757470",
            "Menikah",
            "1",
            "3155330",
            "0",
            "0",
            "1",
            "1654280"
        ],
        [
            "Merry Bendelina Asalaka, S.Si-Teol., M.Pd",
            "P",
            "Kab. Sumba Barat",
            "25 May 1986",
            "Jl. Tampung Penyang",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "082136873478",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Riwu Wulan, S.T, M.Pd",
            "P",
            "Kotawaringin Barat",
            "02 August 1983",
            "Jl. Taurus VII No.345, Kel. Menteng, Kec. Jekan Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081330296185",
            "Menikah",
            "1",
            "3499230",
            "0",
            "0",
            "1",
            "1499600"
        ],
        [
            "Sharon Michelle O Pattiasina, S.Si.Teol., M.Si",
            "P",
            "Ambon",
            "13 October 1995",
            "Hative Kecil",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085244097776",
            "Data Tidak Diketahui",
            "1",
            "2845250",
            "0",
            "0",
            "1",
            "786000"
        ],
        [
            "Julidi Lahagu, S.Th",
            "L",
            "Nias",
            "22 July 1975",
            "Jl. Tampung Penyang RTA.Milono Km.6 Perum Kayzar B5",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081326606089",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "3705380"
        ],
        [
            "Joni Saputra, S.T., M.Kom",
            "L",
            "Palangka Raya",
            "25 June 1981",
            "Jl. Temanggung Tilung I No. 21",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081347583989",
            "Menikah",
            "1",
            "3840375",
            "0",
            "0",
            "1",
            "1140500"
        ],
        [
            "Lelly Sepniwati, M.Hum",
            "P",
            "Kab. Kotawaringin Timur",
            "17 September 1987",
            "Jl. Jati Raya 2 No. 21, Palangka Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081357800859",
            "Belum Menikah",
            "1",
            "3155330",
            "0",
            "0",
            "1",
            "1835685"
        ],
        [
            "Dra. Sri Gunarti Sabdaningrum, M.Pd.K",
            "P",
            "Sambon",
            "16 October 1996",
            "Jl. Tampung Penyang",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "08123387132",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "1890500"
        ],
        [
            "Fernando Dorothius Pongoh, S.Si., M.Si",
            "L",
            "Manado",
            "23 November 1987",
            "Jl. Kalibata IIa Palangka Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "089698597423",
            "Data Tidak Diketahui",
            "1",
            "2934835",
            "0",
            "0",
            "1",
            "691700"
        ],
        [
            "Wirastiani Binti Yusup, M.Pd",
            "P",
            "Sabah",
            "15 April 1994",
            "Jl. Strawbery Raya No 02",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085349959307",
            "Menikah",
            "1",
            "3155330",
            "0",
            "0",
            "1",
            "1706110"
        ],
        [
            "Ratih Sulistyowati, M.Pd",
            "P",
            "Kab. Kotawaringin Barat",
            "29 March 1993",
            "Jl. RA Kartini No. 34 Palangka Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "082220218500",
            "Menikah",
            "1",
            "3155330",
            "0",
            "0",
            "1",
            "1861600"
        ],
        [
            "Lianto, M.Th",
            "L",
            "Jaar",
            "26 January 1982",
            "Jl. Sangga Buana II No.18, Kel. Palangka, Kec. Jekan Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "082157960077",
            "Belum Menikah",
            "1",
            "3840375",
            "0",
            "0",
            "1",
            "1140500"
        ],
        [
            "Yolantya Widyasari, M.I.Kom",
            "P",
            "Palangka Raya",
            "27 July 1992",
            "Jl. Putri Karindang Perum No. 12",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "082155578282",
            "Menikah",
            "1",
            "3155330",
            "0",
            "0",
            "1",
            "1861600"
        ],
        [
            "Pransinartha, M.A",
            "L",
            "Palangka Raya",
            "17 February 1985",
            "Jl. Pipit III No 66 Palangka Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "0816226492",
            "Menikah",
            "1",
            "3288805",
            "0",
            "0",
            "1",
            "1721100"
        ],
        [
            "Dwi Sartica, S.Pd., M.Pd",
            "P",
            "Palangka Raya",
            "02 October 1990",
            "Jl. Tingang VII A-2 Ujung",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "081318151002",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Lukas, M.Pd.K",
            "L",
            "Bengkayang",
            "16 December 1986",
            "Jl. Pemandu Raya Perum Kingland VB No. 13, RT/RW 001/003 Kel. Sabaru Kec. Sabangau Kota Palangka Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081328021129",
            "Menikah",
            "1",
            "2934835",
            "0",
            "0",
            "1",
            "1890500"
        ],
        [
            "Della Gita Van Gobel, M.Pd",
            "P",
            "Minahasa",
            "17 December 1995",
            "Jl. Jaga II, RT/RW 000/000 Kel. Karumenga Kec. Langowan Utara Kab. Minahasa Sulawesi Utara",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085217588040",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "1890500"
        ],
        [
            "Chris Apandie, M.Pd",
            "L",
            "Palangka Raya",
            "24 January 1990",
            "Jl. G Obos No 70",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085249120127",
            "Menikah",
            "1",
            "3059000",
            "0",
            "0",
            "1",
            "1833425"
        ],
        [
            "Isabella Jeniva, M.Si",
            "P",
            "Palangka Raya",
            "08 January 1987",
            "Jl. Sapan XI No. 450",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081253988112",
            "Menikah",
            "1",
            "3155330",
            "0",
            "0",
            "1",
            "1757940"
        ],
        [
            "Ellysa Juang Agusti, M.Pd",
            "P",
            "Kab. Tanah Laut",
            "02 August 1995",
            "JL. Desa Durian Bungkuk, RT.005/ RW.005, Kec. Batu Ampar, Kab. Tanah Laut Kalsel",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "081344539625",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Lisa Maneli, M.Psi",
            "P",
            "Palangka Raya",
            "20 October 1986",
            "JL. Antang II No. 054, RT/RW. 003/018, Kel. Palangka, Kec. Jekan Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "081348155515",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Aprianto Wirawan, M.Th",
            "L",
            "Palangka Raya",
            "25 April 1986",
            "Jl. G.Obos VIII No. 127, RT. 002/ RW.012. Kel. Menteng Kec. Jekan Raya Kota Palangka Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085249508656",
            "Menikah",
            "1",
            "2934835",
            "0",
            "0",
            "1",
            "691700"
        ],
        [
            "Ebariani, M.Th",
            "P",
            "Kab. Barito Timur",
            "11 January 1974",
            "JL. Pinguin VII No. 565, RT.001/012, Kelurahan Bukit Tunggal, Kecamatan Jekan Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "081349167865",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Maria Veronica, M.Ag",
            "P",
            "Kapuas",
            "15 March 1993",
            "Jl. Kapuas Seberang II, RT/RW 003/000 Kel. Sei Pasah Kec. Kapuas Hilir Kapuas",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085249109846",
            "Menikah",
            "1",
            "2934835",
            "0",
            "0",
            "1",
            "691700"
        ],
        [
            "Yosef Darmasatria Bakti, M.Min",
            "L",
            "Kab. Bengkayang",
            "23 May 1968",
            "JL. Menteng VI No. 1 B, RT/RW. 001/011, Kel. Menteng, Kec. Jekan Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "081349477725",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Danella Merdiasi, M.Psi",
            "P",
            "Palangka Raya",
            "02 April 1991",
            "Jl. Rajawali VI No 7",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085249236080",
            "Menikah",
            "1",
            "3155330",
            "0",
            "0",
            "1",
            "1861600"
        ],
        [
            "Deri Susanto, M.Si",
            "L",
            "Kuala Kurun",
            "14 December 1983",
            "Jl. Brigjen Katamso No 76 Kuala Kurun",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "082157365052",
            "Menikah",
            "1",
            "3155330",
            "0",
            "0",
            "1",
            "1861600"
        ],
        [
            "Kukuh Pribadi, M.Psi",
            "L",
            "Palangka Raya",
            "15 April 1983",
            "JL. Beliang No. 40AB, RT/RW. 001/022, Kelurahan Palangka, Kecamatan Jekan Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "08122846492",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Elvira, M.Sn",
            "P",
            "Palangka Raya",
            "03 December 1993",
            "Jl. Damang Bahandang Balau No. 03",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "085248759918",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Octa Maria Sihombing, M.Pd",
            "P",
            "Padangsidimpuan",
            "24 October 1992",
            "Jl. Teuku Umar Gg. Martabe Kel. Losung Kec. Padangsidimpuan Selatan Kota Padangsidimpuan Sumatera Utara",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085296729655",
            "Data Tidak Diketahui",
            "1",
            "2934835",
            "0",
            "0",
            "1",
            "691700"
        ],
        [
            "Frisca Aries BR. Lumban Tobing, S.Pd., M.Sn",
            "P",
            "Medan",
            "06 April 1989",
            "Jl. Tampung Penyang",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081351464159",
            "Menikah",
            "1",
            "2845250",
            "0",
            "0",
            "1",
            "786000"
        ],
        [
            "Anggita Deodora Siten, S.Psi., M.Psi",
            "P",
            "Palangka Raya",
            "14 January 1989",
            "Jl. Temanggung Tandang No. 55",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081349062410",
            "Menikah",
            "1",
            "2845250",
            "0",
            "0",
            "1",
            "786000"
        ],
        [
            "Matius Timan Herdi Ginting, M.Pd.K",
            "L",
            "Malang",
            "15 March 1985",
            "Jl. Surung VI No. D1",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085233336652",
            "Menikah",
            "1",
            "3499230",
            "0",
            "0",
            "1",
            "1499600"
        ],
        [
            "Kalip, M.Pd.K",
            "L",
            "Kab. Sintang",
            "16 February 1977",
            "JL. Rimo Bunga No. 19 Panji Bako, RT/RW. Desa Sitinjo II, Kec. Sitinjo, Kabupaten Dairi - Sidikalang",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "081265816664",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Komala Sari, M.Th",
            "P",
            "Palangka Raya",
            "16 February 1990",
            "JL. Batu Suli VB No. 42B, RT.003/ RW.015, Kelurahan Palangka, Kecamatan Jekan Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "081254066780",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Dr. Yamowa'a Bate'e, M.Th",
            "L",
            "Ombolata/Nias",
            "09 April 1980",
            "Jl. Tangkalasa No 14 Mahir Mahar Km 8",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081573022155",
            "Menikah",
            "1",
            "3472165",
            "0",
            "0",
            "1",
            "4477100"
        ],
        [
            "Dr. Setinawati,M.Th",
            "P",
            "Kuala Kurun",
            "22 February 1976",
            "Jl. Putri Junjung Buih VI No. 4",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081250607111",
            "Menikah",
            "1",
            "3694270",
            "0",
            "0",
            "1",
            "4172990"
        ],
        [
            "Dr. Sanasintani, S.Th., M.Pd",
            "P",
            "Tampa",
            "02 November 1964",
            "Jl. Menteng 22, No.30",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081349156887",
            "Menikah",
            "1",
            "4214865",
            "0",
            "0",
            "1",
            "4125300"
        ],
        [
            "Dr. Evi Mariani,S.Fil, MA",
            "P",
            "Palangka Raya",
            "05 January 1977",
            "Jl. Bajau Ranju No 14",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085390498685",
            "Menikah",
            "1",
            "3961405",
            "0",
            "0",
            "1",
            "935855"
        ],
        [
            "Dr. Sarmauli, M.Th",
            "P",
            "Bengkulu",
            "16 March 1976",
            "Jl. Tampung Penyang Perum Lewu Lampang Batarung No. A/10",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "082156782292",
            "Menikah",
            "1",
            "3723145",
            "0",
            "0",
            "1",
            "4642900"
        ],
        [
            "Dr. Wilson, M.Th",
            "L",
            "Pelaik-Sintang",
            "30 June 1969",
            "Jl. RTA.Milono,km.9,5 (jl.Taheta, Blok D/I), Kel. Kereng Bangkirai, Kec. Sebangau",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "082111201995/08125664869",
            "Menikah",
            "1",
            "3920270",
            "0",
            "0",
            "1",
            "1056400"
        ],
        [
            "Dr. Agus Surya, M.Th.",
            "L",
            "Pontianak",
            "26 March 1977",
            "Jl. Temanggung Tilung VII, Kel. Menteng, Kec. Jekan Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "082116451454",
            "Menikah",
            "1",
            "3840375",
            "0",
            "0",
            "1",
            "4683500"
        ],
        [
            "Drs. Rudie, M.Pd",
            "L",
            "Kapuas Hulu",
            "10 August 1964",
            "Jl. Sapan XI No. 70 RT/RW: 008/009, Kel. Bukit Tunggal, Kec. Jekan Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "082155042748",
            "Menikah",
            "1",
            "4784055",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Sugiyanto, S.PAK., M.Th",
            "L",
            "Tumbang Talaken",
            "23 October 1961",
            "Jl.Perak II No. 23 Kereng bangkirai, Kec. Jekan Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081254608383/082350456789",
            "Menikah",
            "1",
            "4589915",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Dr. Stephanus Prihadi, M.Th",
            "L",
            "Pati",
            "01 January 1962",
            "Perum Tayu Kulon Sejahtera Blok B No. 6 Tayu, Kel. Giling, Kec. Gunungwungkal, Pati/ Doho ujung Kalampangan",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085325262933",
            "Menikah",
            "1",
            "4589915",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Yuel,S.PAK, M.Th",
            "L",
            "Puruk Cahu",
            "19 February 1965",
            "Jl. Pratama No.5 RTA.Milono Km.7, Kel. Menteng, Kec. Jekan Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081251620870",
            "Menikah",
            "1",
            "4347580",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Agus Budi Handoko,S.Th, M.Sn",
            "L",
            "Surakarta",
            "12 August 1975",
            "Jl. Sapan Raya, Kel. Bukit Tunggal, Kec. Jekan Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081390046003",
            "Menikah",
            "1",
            "0",
            "0",
            "0",
            "1",
            "2591500"
        ],
        [
            "Indah Sriwijayanti, M.Si.Teol",
            "P",
            "Panjirejo",
            "03 January 1986",
            "Jl. Damang Leman No.2, Kel. Menteng, Kec. Jekan Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085828391314",
            "Menikah",
            "1",
            "0",
            "0",
            "0",
            "1",
            "2591500"
        ],
        [
            "Rinto Hasiholan Hutapea, M.Th",
            "L",
            "Sibolga",
            "10 November 1981",
            "Jl. Jati Raya 1 Palangka Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081310083870",
            "Menikah",
            "1",
            "3499230",
            "0",
            "0",
            "1",
            "1499600"
        ],
        [
            "Jeffry Simson Supardi, M.Psi",
            "L",
            "Malang",
            "21 November 1980",
            "Jl. Jati No.80, Kel. Panarung, Kec. Pahandut",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081349208808",
            "Menikah",
            "1",
            "3840375",
            "0",
            "0",
            "1",
            "1036840"
        ],
        [
            "Lilyantie,S.Th, M.Si",
            "P",
            "Palangka Raya",
            "24 March 1984",
            "Jl. Yos Sudarso No. 043",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081251567699",
            "Menikah",
            "1",
            "3840375",
            "0",
            "0",
            "1",
            "1140500"
        ],
        [
            "Karolina, S.Th, M.Si",
            "P",
            "Palangka Raya",
            "22 December 1974",
            "Jl. RTA Milono Km. 8",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085845156203",
            "Menikah",
            "1",
            "3840375",
            "0",
            "0",
            "1",
            "1036840"
        ],
        [
            "Eva Inriani, M.Th",
            "P",
            "Gunung Mas",
            "29 October 1986",
            "Jl. Mutiara No. 16, Kel. Bukit Tunggal, Kec. Jekan Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085828633439",
            "Menikah",
            "1",
            "3155330",
            "0",
            "0",
            "1",
            "1861600"
        ],
        [
            "Desi Natalia, M.Si",
            "P",
            "Palangka Raya",
            "22 December 1985",
            "Jl. G.Obos VIII Komplek 4 Sekawan No. 01",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081348930269",
            "Menikah",
            "1",
            "3155330",
            "0",
            "0",
            "1",
            "1783855"
        ],
        [
            "Daido Tri Sampurna Lumban Raja, M.Th",
            "L",
            "Jakarta",
            "22 November 1988",
            "Jl. Perumahan Graha Nusa Batam Blok No 9",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "082159207758",
            "Menikah",
            "1",
            "3155330",
            "0",
            "0",
            "1",
            "1861600"
        ],
        [
            "Ni Nyoman Astrini Utami, M.Hum",
            "P",
            "Kab. Ganyar",
            "08 December 1992",
            "Jl. Yos Sudarso No 112 Palangka Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Hindu",
            "081257585150",
            "Menikah",
            "1",
            "0",
            "0",
            "0",
            "1",
            "2591500"
        ],
        [
            "Putra Andino Nugrahhu, M.Pd",
            "L",
            "Banjarmasin",
            "30 September 1992",
            "JL. Rajawali VI NO. 8",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085249205056",
            "Menikah",
            "1",
            "0",
            "0",
            "0",
            "1",
            "2591500"
        ],
        [
            "Defri Triadi, M.Si",
            "L",
            "Palangka Raya",
            "16 October 1990",
            "JL. Tiung II No. 19",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081244525709",
            "Menikah",
            "1",
            "0",
            "0",
            "0",
            "1",
            "2591500"
        ],
        [
            "Tiavone Theressa Andiny, M.Si",
            "P",
            "Palangka Raya",
            "01 March 1988",
            "Jl. Sepakat III No H77 Perum Bangas Permai",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085348334004",
            "Menikah",
            "1",
            "3155330",
            "0",
            "0",
            "1",
            "1732025"
        ],
        [
            "Dr.Silipta, S.PAK., M.Th",
            "P",
            "Kotawaringin Timur",
            "18 September 1966",
            "Jl. Pratama No.5 RTA.Milono Km.7",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081352837447",
            "Menikah",
            "1",
            "4171165",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Latupeirissa Risvan, S.Si.Teol, M.Si",
            "P",
            "Merauke",
            "20 April 1986",
            "Jl. Tampung Penyang",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085343132666",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2591500"
        ],
        [
            "Reynhard Malau, M.Th",
            "L",
            "Jakarta",
            "19 September 1989",
            "Jl. RTA Milono Km 4,5",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085286503260",
            "Belum Menikah",
            "1",
            "3027270",
            "0",
            "0",
            "1",
            "594400"
        ],
        [
            "Cristi Devi Darnita, M.A.",
            "P",
            "Palangka Raya",
            "29 July 1993",
            "Jl. Yos Sudarso No. 978",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "082153739201",
            "Menikah",
            "1",
            "0",
            "0",
            "0",
            "1",
            "1890500"
        ],
        [
            "Yane Octavia Rismawati Wainarisi, M.Th",
            "P",
            "Pontianak",
            "08 October 1988",
            "Jl. Sukamakmur RT/RW 022/010 Kel. Air Batu Kec. Talang Kelapa Kab. Banyuasin Sumatera Selatan",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085210984401",
            "Data Tidak Diketahui",
            "1",
            "0",
            "0",
            "0",
            "1",
            "691700"
        ],
        [
            "Alfonso Munte, M.Pd.K",
            "L",
            "Palembang",
            "19 March 1989",
            "Jl. Pelajar IV No.11a Palangka Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085393594845",
            "Belum Menikah",
            "1",
            "0",
            "0",
            "0",
            "1",
            "1890500"
        ],
        [
            "Yola Pradita, M.Th",
            "P",
            "Kapuas",
            "14 January 1993",
            "Jl. Hiu Putih XII, RT/RW 006/010 Kel. Bukit Tunggal Kec. Jekan Raya Kota Palangka Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "082251315058",
            "Menikah",
            "1",
            "2934835",
            "0",
            "0",
            "1",
            "616080"
        ],
        [
            "Fitrisiswanty, S.E., M.Si",
            "P",
            "Palangka Raya",
            "03 September 1978",
            "Jl. Cendana No. 16",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085249192799",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "4551000"
        ],
        [
            "Friska Muliani, S.IP.",
            "P",
            "Palangka Raya",
            "15 July 1981",
            "Jl. Darmosugondo Gg. Rahmat No.02",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081349209896",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "4551000"
        ],
        [
            "Agri Apriliando, S.T",
            "L",
            "Palangka Raya",
            "29 April 1993",
            "Jl. Badak IX No 10 B Palangka Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085249441182",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "3236025"
        ],
        [
            "Arther Evert Samuel, S.E",
            "L",
            "Jakarta",
            "24 April 1989",
            "Jl. Mutiara V No. 16",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085252973618",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "3319000"
        ],
        [
            "Kronika Novie Welianti, S.H",
            "P",
            "Kuala Kapuas",
            "24 April 1987",
            "Jl. Kalibata Blok D Jalur 1 No. K2 Palangka Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085251472666/08115246699",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "3319000"
        ],
        [
            "Raymond Gomgom Sitorus, S.Kom",
            "L",
            "Palangka Raya",
            "01 January 1993",
            "Jl. Bromo No. 15, RT/RW 03/14 Kel. Palangka Kec. Jekan Raya Kota Palangka Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081345374932",
            "Belum Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "3302405"
        ],
        [
            "Devid Prianata, S.E",
            "L",
            "Barito Selatan",
            "24 December 1983",
            "Jl. G.Obos VIII Komplek 4 Sekawan No. 01",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081348997245",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "4186920"
        ],
        [
            "Ika Agustina, S.E., M.Si.",
            "P",
            "Palangka Raya",
            "15 August 1986",
            "Jl. Sultan Badarudin No. 28 Palangka Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085246496959",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "3781000"
        ],
        [
            "Junadi Djojoatmodjo, S.E., M.Si.",
            "L",
            "Palangka Raya",
            "17 June 1983",
            "Jl. RTA.Milono Km.8 Perum Fajar Permai I No. 25",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085249331562",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "3781000"
        ],
        [
            "Gracesilya Veronica Barus, S.E.",
            "P",
            "Buntut Bali, Kab.Katingan",
            "22 April 1982",
            "Jl. G.Obos VIIIB",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "082255343932",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "3319000"
        ],
        [
            "Trissia Noveta, S.Hut.",
            "P",
            "Kasongan",
            "26 November 1979",
            "Jl. Aries V No. 22",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085346672827",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2928000"
        ],
        [
            "Meilena Salom Muhaling, S.Si.",
            "P",
            "Banyumas",
            "05 May 1981",
            "Jl. RTA.Milono Km.8 Perumahan Kereng Indah Permai",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "0816288885",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Jhonny Rouland, S.E.",
            "L",
            "Jakarta",
            "18 March 1980",
            "Jl. Basir Jahan XII RTA.Milono Km.9",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081254004855",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2928000"
        ],
        [
            "Edward Dabukke, M.Pd",
            "L",
            "Dairi",
            "09 November 1979",
            "Jl. Matal Blok B No. 26 Perum Matal RTA. Milono Km. 9",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081317000368",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2752320"
        ],
        [
            "Jayewardeni, S.Ds",
            "L",
            "Barito Selatan",
            "30 May 1983",
            "Jl. Temanggung Tilung XXII BTN No. 35 Palangka Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081351226044",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2702000"
        ],
        [
            "Yudeniririn Kunanto, S.IP., M.Si",
            "P",
            "Palangka Raya",
            "30 January 1987",
            "Jl. Eboni No. 09 Palangka Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081253845587",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2634450"
        ],
        [
            "Netanya, A.Md., S.Pd.K.",
            "P",
            "Tumbang Lapan",
            "06 July 1977",
            "Jl. Kalibata 1 No. 7",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081352843088",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2913360"
        ],
        [
            "Nanisusantie, S.Th.",
            "P",
            "Palangka Raya",
            "14 March 1987",
            "Jl. Cilik Riwut Km.29 No.23",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "082240577614",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2869440"
        ],
        [
            "Andika Petrus, S.Kep., M.A.P",
            "L",
            "Kurun",
            "13 February 1988",
            "Jl. Ais Nasution Kec. Kurun",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "082153225523",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2702000"
        ],
        [
            "Philips Yacobus Tampa, S.E., M.A.P",
            "L",
            "Minahasa",
            "15 August 1978",
            "Jl. Tangkasiang No.002",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "08115215878",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2928000"
        ],
        [
            "Ani Wawei, A.Md.",
            "P",
            "Buntok",
            "09 January 1978",
            "Jl. Haruan No.6",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085387709588",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2702000"
        ],
        [
            "Julianto, SE",
            "L",
            "Gunung Mas",
            "17 April 1991",
            "Jl. Suka Mangkahai Gg. Padat Karya RT. 3 Mandomai Kapuas Barat",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Islam",
            "082251685370",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2928000"
        ],
        [
            "Etik Purnama, S.S.I",
            "P",
            "Barito Timur",
            "15 March 1986",
            "Jl. Garuda X No.21",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "081345513050",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2928000"
        ],
        [
            "Natalis Ingat",
            "L",
            "Ampah",
            "26 December 1972",
            "Jl. Unkrip No.22 Palangka Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "085249028643",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2493000"
        ],
        [
            "Reflie Ventie Runtu",
            "L",
            "Minahasa",
            "07 January 1969",
            "Jl. RTA.MilonoKm.7 Langkai Permai III No.5",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PNS",
            "Kristen",
            "089696222232",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2443140"
        ],
        [
            "Kurniawan Netanyahu, M.A",
            "L",
            "Kab. Kapuas",
            "03 November 1996",
            "Jl. Garuda No 014",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "081391451588",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Nova Lady Simanjuntak, M.Pd",
            "P",
            "Tebing Tinggi",
            "27 November 1993",
            "Jl. Tampung Penyang V No. 23",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "081222406225",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Agus Sutrisno Muljono, S.Psi., M.Si",
            "L",
            "Cirebon",
            "24 November 1979",
            "JL. Raden Saleh I No. 7A, RT/RW. 004/007, Kel. Menteng, Kec. Jekan Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "081221953123",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Citra Dewi, M.Th",
            "P",
            "Kab. Pulang Pisau",
            "23 December 1969",
            "JL. Bajau Ranju No. 38 B, RT/RW. 003/010, Kel. Langkai, Kec. Pahandut",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "081256064604",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Yuherlita Marneci, M.Pd.K",
            "P",
            "Kab. Katingan",
            "29 March 1990",
            "JL. Piranha 8, RT/RW. 00/016, Kel/Desa. Bukit Tunggal, Kec. Jekan Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "083141831248",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Agus Gelu Libur, S.Pd.K",
            "L",
            "Kab. Flores Timur",
            "08 August 1989",
            "JL. Lamtoro Gung II Blok A. No A 11",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "082148532744",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Elisa Theresia, S.Th",
            "P",
            "Kab. Kapuas",
            "11 December 1989",
            "JL. Matal Gg Sariau No. 07 RT/RW. 004/001 Kel. Sabaru, Kec. Sabangau",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "085349415836",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Hendayani, S.T",
            "P",
            "Kab. Barito Timur",
            "04 August 1993",
            "JL. Lamtoro Gung, Jl. Haka 31 No. 1595",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "082136099148",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Loure Florentina, S.T",
            "P",
            "Palangka Raya",
            "02 May 1996",
            "JL. G.Obos 25 Jl. Abimanyu No. 41",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "081347977601",
            "Belum Menikah",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Yan Patria Pandu Arista, S.Kom",
            "L",
            "Kab. Karanganyar",
            "27 March 1991",
            "JL. Tampung Penyang Perum Kayzar Estate No. A.01, Kel. Menteng, Kec. Jekan Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "081347812994",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Chrismas Debianto, S.Pd.",
            "L",
            "Banjarmasin",
            "21 December 1996",
            "Jl. Sulawesi Gang Nusantara No. 48, Kota Palangka Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "082352127683",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Remi Anggela, S.Pd.K.",
            "P",
            "Palangka Raya",
            "09 December 1985",
            "Jl. Bukit Pinang No. 160",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "082255357080",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Andika Silviana, S.T.",
            "P",
            "Palangka Raya",
            "15 April 1994",
            "Jl. Temannggung Kanyapi II B",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "085246911417",
            "Belum Menikah",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Yafet Bintang Fajar Wailan Sinjal, S.Sn.",
            "L",
            "Jakarta Selatan",
            "17 November 1986",
            "Jl. Green Kemang Residence Blok B, No. 11, RT.002/RW.01, Kel. Pabuaran, Kec. Kemang, Kab. Bogor, Jawa Barat",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "085778138939",
            "Belum Menikah",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Deniel Marcho Eli Katparu, S.T.",
            "L",
            "Gunung Mas",
            "16 March 1996",
            "Jl. Sei Rangit No. 02",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "082352695266",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Novita Erianti, S.T.",
            "P",
            "Palangka Raya",
            "14 November 1989",
            "Jl. B.Koetin BBA No. 71",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "082250239819",
            "Belum Menikah",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "Dr. Agustiman, M.Min",
            "L",
            "Kab. Kapuas",
            "18 August 1976",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "081352715074",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "5183000"
        ],
        [
            "Antonius Prinando Saputra, S.Pd.K",
            "L",
            "Batapah",
            "27 October 1991",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "082256006639",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2928000"
        ],
        [
            "Beni, A.Md, KA",
            "L",
            "Palangka Raya",
            "18 September 1996",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "081385253919",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2702000"
        ],
        [
            "Depi, S.Pd.K",
            "L",
            "Maliku",
            "27 February 1987",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "085820463040",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2928000"
        ],
        [
            "Deprianto, S.Pd",
            "L",
            "Tewang Pajangan",
            "01 January 1994",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "0895338860868",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "1",
            "3319000"
        ],
        [
            "Erick Kristianson, S.Pd",
            "L",
            "Maliku Baru",
            "21 July 1985",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "082145500971",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2928000"
        ],
        [
            "Frilli Sua Renro, S.Pd.K",
            "L",
            "Palingkau",
            "23 April 1983",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "0895349690019",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2928000"
        ],
        [
            "Hari Sonedi, S.Hut",
            "L",
            "Palangka Raya",
            "24 September 1971",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "081321200990",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "3319000"
        ],
        [
            "Hendro, S.Pd.K",
            "L",
            "Bahaur",
            "09 February 1985",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "081357042409",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2928000"
        ],
        [
            "‌I Gusti Ayu Aldyth Alodia, S.Kom",
            "L",
            "Tumbang Samba",
            "09 June 1995",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "085249168680",
            "Belum Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "3319000"
        ],
        [
            "‌Jonny Meyer, M.Th",
            "L",
            "Jakarta",
            "01 June 1976",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "082251565977",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "1890500"
        ],
        [
            "Dr. Kilat Kasanang, M.Th",
            "L",
            "Kab. Kapuas",
            "28 September 1979",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "085249043480",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2591500"
        ],
        [
            "Liven Stifanus, SP",
            "L",
            "Sampit",
            "22 October 1984",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "085252900898",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2928000"
        ],
        [
            "Meila Frensisca, S.Kom",
            "P",
            "Palangka Raya",
            "06 May 1990",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "081349209896",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "1",
            "3319000"
        ],
        [
            "Monica augina, S.E",
            "P",
            "Palangka Raya",
            "14 August 1994",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "085349475410",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "3319000"
        ],
        [
            "Sandro, S.Th",
            "L",
            "Mandomai",
            "18 April 1982",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "085249056673",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2928000"
        ],
        [
            "Setiawan Yardi",
            "L",
            "Palangka Raya",
            "17 September 1982",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "082255907417",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2493000"
        ],
        [
            "Sinta Nurlela, M.Pd",
            "P",
            "Kab. Gunung Mas",
            "19 June 1984",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "085249130233",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "1",
            "1890500"
        ],
        [
            "Trikashu Awatnu, S.Kom",
            "L",
            "Kab. Gunung Mas",
            "03 August 1989",
            "Jl G. Obos III No. 94 Palangka Raya",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "085387831111",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2928000"
        ],
        [
            "Vinny Maria Yulianty, S.T",
            "P",
            "Kab. Kapuas",
            "09 July 1991",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "082155791301",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "3319000"
        ],
        [
            "Vivin",
            "L",
            "Palangka Raya",
            "24 April 1985",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2493000"
        ],
        [
            "Wardana Kussuma, S.Pd",
            "L",
            "Palangka Raya",
            "12 January 1989",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "PPPK",
            "Kristen",
            "08115246677",
            "Menikah",
            "0",
            "0",
            "0",
            "0",
            "1",
            "2928000"
        ],
        [
            "‌Andre Marcel Toisuta, M.A",
            "L",
            "Ambon",
            "26 March 1993",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "CPNS",
            "Kristen",
            "0895366234555",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "‌Andreas Setiawan, M. Th",
            "L",
            "Cirebon",
            "09 October 1996",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "CPNS",
            "Kristen",
            "08562191827",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "‌Dewani Dama Shinta, M.Si",
            "P",
            "Palangka Raya",
            "04 July 1992",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "CPNS",
            "Kristen",
            "081250900465",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "‌Yoges Mahendra Saragih, M.Pd",
            "L",
            "Kabanjahe",
            "11 February 1999",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "CPNS",
            "Kristen",
            "085658366842",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "‌Evelline Kristiani, S.Kom",
            "P",
            "Tumbang Manggo",
            "30 March 1996",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "CPNS",
            "Kristen",
            "085173380671",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "‌Hosea Paniroi Panjaitan, S.E",
            "L",
            "Jambi",
            "08 February 1992",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "CPNS",
            "Kristen",
            "081241324232",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "‌Imelda Apriani Barus, S.E",
            "P",
            "Sumbul",
            "20 April 1992",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "CPNS",
            "Kristen",
            "081263372866",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ],
        [
            "‌Vita Novita, S.E",
            "P",
            "Balikpapan",
            "24 November 1994",
            "",
            "",
            "Palangka Raya",
            "Kalimantan Tengah",
            "CPNS",
            "Kristen",
            "085350002950",
            "Data Tidak Diketahui",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        ]
    ];
    public function run(): void
    {
        foreach ($this->employees as $employee) {
            DB::table('employees')->insert([
                'id' => $employee[0],
                'nik' => $employee[1],
                'nip' => $employee[2],
                'nidn' => $employee[3],
                'nuptk' => $employee[4],
                'nama_lengkap' => $employee[5],
                'gender' => $employee[6],
                'birth_place' => $employee[7],
                'birth_date' => Carbon::parse($employee[8])->format('Y-m-d'),
                'address' => $employee[9],
                'district' => $employee[10],
                'city' => $employee[11],
                'province' => $employee[12],
                'employee_status' => $employee[13],
                'religion' => $employee[14],
                'mobile_num' => $employee[15],
                'status_pernikahan' => $employee[16],
                'status_sertifikasi' => (bool)$employee[17],
                'nominal_sertifikasi_yg_diterima' => $employee[18],
                'status_remonerasi' => FALSE,
                'nominal_remonerasi' => 0,
                'status_tukin' => (bool)$employee[21],
                'nominal_tukin' => $employee[22],
                'status_selkin' => FALSE,
                'nominal_selkin' => 0,
                'statistic_num' => '',
                'nama_institusi' => 'IAKN Palangka Raya',
                'institution_category' => 'Institut',
                'tgl_data' => Carbon::now()->startOfMonth(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
        // foreach ($this->employees as $employee) {
        //     DB::table('employees')->insert([
        //         'nik' => $employee[1],
        //         'nip' => $employee[2],
        //         'nidn' => $employee[3],
        //         'nuptk' => $employee[4],
        //         'nama_lengkap' => $employee[5],
        //         'gender' => $employee[6],
        //         'birth_place' => $employee[7],
        //         'birth_date' => Carbon::parse($employee[8])->format('Y-m-d'),
        //         'address' => $employee[9],
        //         'district' => $employee[10],
        //         'city' => $employee[11],
        //         'province' => $employee[12],
        //         'employee_status' => $employee[13],
        //         'religion' => $employee[14],
        //         'mobile_num' => $employee[15],
        //         'status_pernikahan' => 'Data Tidak Diketahui',
        //         'status_sertifikasi' => (bool)$employee[17],
        //         'nominal_sertifikasi_yg_diterima' => 0,
        //         'status_remonerasi' => FALSE,
        //         'nominal_remonerasi' => 0,
        //         'status_tukin' => TRUE,
        //         'nominal_tukin' => 0,
        //         'status_selkin' => FALSE,
        //         'nominal_selkin' => 0,
        //         'statistic_num' => '',
        //         'nama_institusi' => $employee[26],
        //         'institution_category' => $employee[27],
        //         'tgl_data' => Carbon::now()->addMonthNoOverflow()->startOfMonth(),
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ]);
        // }
    }
}
